version: '3'

services:
  nginx:
    container_name: fullstack-docker_nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./server/nginx/dev:/etc/nginx/conf.d
      - web:/app
    ports:
      - "3000:80"
    command: [nginx-debug, '-g', 'daemon off;']
  web:
    container_name: fullstack-docker_web
    image: web
    volumes:
      - web:/app
    build:
      context: ./web
      dockerfile: ./Dockerfile
  api:
    container_name: fullstack-docker_api
    image: api
    volumes:
      - api:/app
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      - PORT=3001
    expose:
      - 3001
    ports:
      - "3001:3001"

volumes:
  web:
  api:
